name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: window-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v5.0.0

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild PhysicsGame.sln /p:Configuration=Release
